### ISSUE TITLE
Problem creating vacancy, while reading from user input structure

### ISSUE THREAD

**Issue by ganesh028** [pydii/pydii#7]
Dear Developer,
I tried to make read the input structure. It seems it has some problems with creating vacancy structures.

I was using the following structure as POSCAR input: [https://materialsproject.org/materials/mp-1330/](url)

Here is the error:

Traceback (most recent call last):
  File "/home/gnayak028/software/anaconda3/bin/gen_def_structure", line 11, in <module>
    load_entry_point('pydii==1.9.0', 'console_scripts', 'gen_def_structure')()
  File "/home/gnayak028/software/anaconda3/lib/python3.7/site-packages/pydii-1.9.0-py3.7.egg/pydii/scripts/gen_def_structure.py", line 258, in im_vac_antisite_def_struct_gen
    struct_file=args.struct)
  File "/home/gnayak028/software/anaconda3/lib/python3.7/site-packages/pydii-1.9.0-py3.7.egg/pydii/scripts/gen_def_structure.py", line 98, in vac_antisite_def_struct_gen
    vac = Vacancy(structure=prim_struct, defect_site=site)
  File "/home/gnayak028/software/anaconda3/lib/python3.7/site-packages/pymatgen/analysis/defects/core.py", line 54, in __init__
    self._multiplicity = multiplicity if multiplicity else self.get_multiplicity()
  File "/home/gnayak028/software/anaconda3/lib/python3.7/site-packages/pymatgen/analysis/defects/core.py", line 180, in get_multiplicity
    raise ValueError("Site {} is not in bulk structure! Cannot create Vacancy object.".format(self.site))
ValueError: Site [ 0.       -1.017259 -1.017259] Al is not in bulk structure! Cannot create Vacancy object.

Regards,
Ganesh

**Comment by enze-chen** [comment]
Dear Ganesh,

Thank you for reporting this issue and I apologize for not getting back to you sooner.

Unfortunately, I was unable to reproduce this error. Are you using the latest version of pydii?

For example, since the link you gave was a materials project structure, I built pydii (e.g. `pip install .` in the main directory) and used the command:

`gen_def_structure --mpid mp-1330`

which produced five relevant directories (two of them corresponding to vacancies). I could also download the structure from the website and use

`gen_def_structure --struct AlN.cif`

to the same effect. It sounds like maybe you used your own POSCAR though? If you could please elaborate or share your input file, I might be able to try it out myself.

Best,
Enze

**Comment by ganesh028** [comment]
Dear Enze, 
Sorry for the late reply. I was trying to run it in my calculations. You are right it takes from the calculations from the structure with .cif file. I managed that. Another problem I have the following.

During the profile scan with the structure it requires the mpid:

gen_def_profile -T 300 --file AlN/_raw_defect_energy.json

which produced the following error:
===========
ERROR: mpid is not given.
===========

Again, maybe that can be solved as the command '--formula ':

gen_def_profile --formula AlN -T 300 --file AlN/_raw_defect_energy.json

Also I tried the following command (simply putting mpid):

gen_def_profile --mpid mp-1330 -T 300 AlN/_raw_defect_energy.json

In both the above case, the error I got is the following:


No trial chemical potential is given.
Traceback (most recent call last):
  File "/home/ganesh/.local/bin/gen_def_profile", line 11, in <module>
    load_entry_point('pydii==1.9.0', 'console_scripts', 'gen_def_profile')()
  File "/home/ganesh/.local/lib/python3.6/site-packages/pydii/scripts/gen_def_profile.py", line 117, in im_vac_antisite_def_profile
    conc_dat, en_dat, mu_dat = get_def_profile(args.mpid, args.temp, file_name)
  File "/home/ganesh/.local/lib/python3.6/site-packages/pydii/scripts/gen_def_profile.py", line 36, in get_def_profile
    antisites, T, plot_style='gnuplot')
  File "/home/ganesh/.local/lib/python3.6/site-packages/pydii/dilute_solution_model.py", line 679, in compute_defect_density
    structure, e0, vac_defs, antisite_defs, T, trial_chem_pot=trial_chem_pot)
  File "/home/ganesh/.local/lib/python3.6/site-packages/pydii/dilute_solution_model.py", line 401, in dilute_solution_model
    mu_vals = compute_mus_by_search()
  File "/home/ganesh/.local/lib/python3.6/site-packages/pydii/dilute_solution_model.py", line 300, in compute_mus_by_search
    raise ValueError()
ValueError

Please help me to solve this.

Thank you in advance,

Regards,
Ganesh

**Comment by enze-chen** [comment]
Dear Ganesh,

Thank you for the detailed reply. I'm glad you were able to generate your structures.

With regards to the **ERROR** that you reported, your conclusion is correct. Either `--mpid` or `--formula` is required, even if `--file` is supplied. This is poorly documented. Sorry about that.

As to the second `ValueError` that you're getting, I **was** able to reproduce it. Thanks for pointing it out. At the moment I will not be able to do any further testing as NERSC is down, but I can offer a few comments.

- I'm pretty unfamiliar with `AlN` and noticed that it was an insulator with a pretty sizable bandgap. Taking this into account...
    - The default VASP settings won't be very suitable for your problem. Hopefully the ones I used for my test calculations were OK. I'm assuming you checked this though for your own calculations.
    - Perhaps more importantly, this library was based off of the dilute solution model (see [this paper](https://link.aps.org/doi/10.1103/PhysRevB.63.094103)) and I just don't know how suitable it is for nonmetallic structure with such strong covalent bonds.
- It seems like a numeric problem, and for this I apologize as it's on us.
    - I noticed the defect excitation energies were quite large, and so maybe somewhere in an exponential the terms are being reduced to zero or blowing up.
    - The current method of obtaining the solution relies on the `sympy` library and a bit of guess-and-check, so it's totally possible that the solution to your problem is outside of the bounds that the code currently considers.

Truthfully, I'm not sure how quickly I'll be able to get to the root of this issue, but I will try my best. Happy to hear your thoughts on any of the above.

Cheers,
Enze

**Comment by ganesh028** [comment]
Dear Enze,
Thank you very much for the quick reply. 

It will be very helpful if you could help with this numeric problem. 

Again, I will test it for the metallic system like TiN and maybe we can come to a conclusion about this numeric problem you are indicating.

Thank you very much for your help for now and the future.

Regards,
Ganesh

**Comment by mbkumar** [comment]
To follow up on what Enze mentioned regarding the error in
compute_mus_by_search, the method used to find mus was based on brute-force
grid search.
I implemented it at a time I was not very familiar with root finding and
also with chemical potentials. Better techniques may be available, but if
the grid search fails, it means there is no numerical solution to the
problem.

Though it looks like a solver error, essentially it implies a solution to
chemical potentials could not be found meaning the problem is ill-defined.
Ill-defined problem could imply two things:
1) There are some issues with the parameters supplied (You might have
incorrectly computed some of the parameters). It's so easy to introduce
errors in defect calculations.
2) Dilute Solution Method is not applicable for the system.

#2 is a very possible scenario because the applicability of dilute solution
model is quite limited. Special quasi-random structure (SQS) method is more
stable and you may attempt to solve your problem using SQS.

Bharat Medasani

Engineer
Princeton Plasma Physics Lab (PPPL)

**Comment by ganesh028** [comment]
Dear Enze and Bharat,
Thank you very much for your support and reply.

I am testing it in the case of TiN. I will report the results.

One more thing. I wonder why there are not interstitial sites (as a solute as well as solvent) as a defect concentration. Could you able help me with the following?

Thank you very much in advance!!

Best Regards,
Ganesh
